// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6oYGA_P35NA8cbx8_nASxkR-_7AOAwao',
    appId: '1:1080260447345:web:15f3d1b206d99a21331fd0',
    messagingSenderId: '1080260447345',
    projectId: 'mapeador-de-qualidade-de-vida',
    authDomain: 'mapeador-de-qualidade-de-vida.firebaseapp.com',
    storageBucket: 'mapeador-de-qualidade-de-vida.firebasestorage.app',
    measurementId: 'G-PQGM7KG259',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUuKuWQYu2WX96H_5KQaaEGgweTm4X9Co',
    appId: '1:1080260447345:android:ae78b71c4da63cd3331fd0',
    messagingSenderId: '1080260447345',
    projectId: 'mapeador-de-qualidade-de-vida',
    storageBucket: 'mapeador-de-qualidade-de-vida.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2lN_jXzl9AtOwkxrh9pkEB7NEHHTwNUE',
    appId: '1:1080260447345:ios:9af70b98e7c70200331fd0',
    messagingSenderId: '1080260447345',
    projectId: 'mapeador-de-qualidade-de-vida',
    storageBucket: 'mapeador-de-qualidade-de-vida.firebasestorage.app',
    iosBundleId: 'com.example.mapaBiriguiFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2lN_jXzl9AtOwkxrh9pkEB7NEHHTwNUE',
    appId: '1:1080260447345:ios:9af70b98e7c70200331fd0',
    messagingSenderId: '1080260447345',
    projectId: 'mapeador-de-qualidade-de-vida',
    storageBucket: 'mapeador-de-qualidade-de-vida.firebasestorage.app',
    iosBundleId: 'com.example.mapaBiriguiFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6oYGA_P35NA8cbx8_nASxkR-_7AOAwao',
    appId: '1:1080260447345:web:7670b6f8008fefba331fd0',
    messagingSenderId: '1080260447345',
    projectId: 'mapeador-de-qualidade-de-vida',
    authDomain: 'mapeador-de-qualidade-de-vida.firebaseapp.com',
    storageBucket: 'mapeador-de-qualidade-de-vida.firebasestorage.app',
    measurementId: 'G-48K05G79DT',
  );
}
